import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os

class AJWebnovaMail:
    def __init__(self, email=None, password=None):
        # For Gmail, use an "App Password", not your main password
        self.email = email or os.getenv("SENDER_EMAIL")
        self.password = password or os.getenv("SENDER_PASSWORD")
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587

    def send_proposal(self, receiver_email, client_name, proposal_content):
        """Sends the High-Ticket proposal generated by the Closer Agent."""
        if not self.email or not self.password:
            raise ValueError("Email credentials missing! Set SENDER_EMAIL and SENDER_PASSWORD.")

        message = MIMEMultipart()
        message["From"] = f"AJ Webnova <{self.email}>"
        message["To"] = receiver_email
        message["Subject"] = f"Strategic Digital Growth Audit for {client_name}"

        body = f"Hello {client_name},\n\n{proposal_content}\n\nBest regards,\n\nVikas A J\nFounder, AJ Webnova"
        message.attach(MIMEText(body, "plain"))

        try:
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.email, self.password)
            server.send_message(message)
            server.quit()
            return True
        except Exception as e:
            print(f"Mail Error: {e}")
            return False
